### ISSUE TITLE
Azure Search Index Size Limit Notification

### ISSUE THREAD

**Issue by adamkjonesmesh** [Azure-Samples/search-dotnet-getting-started#28]
Is there any way to know when we have hit or are getting close to hitting the size limit on our index?  Say our index size limit is 50 MB (Free Tier).  If our index size gets to 50 MB, what happens?  I cannot find any documentation addressing this.  Do further indexes get rejected?  Is there any way to notify of this situation before it happens?  Is there any way to autoscale?

Thanks.

**Comment by bitsforthought** [comment]
@adamkjonesmesh Your question has been answered on Yammer.

I'm closing this issue since it is not related to the .NET sample apps.

In the future I'd encourage you to ask general questions like this on StackOverflow and tag them with "azure-search". We monitor that site and respond to questions regularly. Plus, it is a public forum so the answers will benefit other Azure Search customers too (unlike the Yammer group, which is private). Thanks!

**Comment by adamkjonesmesh** [comment]
Sounds good, thanks.
