### ISSUE TITLE
Azure Search not working with Unicode Code characters between 296-304(including)

### ISSUE THREAD

**Issue by Deepakgullipalli** [Azure-Samples/search-dotnet-getting-started#51]
When tried to search documents with words containing these unicode characters, results are not fetched, it works fine with english 'i', but not latin i with dot

**Comment by HeidiSteen** [comment]
It doesn't sound like this issue is specific to one of our samples, so I'll close it since there is nothing actionable on that content.  Regarding the query issue you describe above, the default analyzer removes diacritics. You can try other language analyzers or configure a custom analyzer to preserve those characters.
